[[N2QN1]]
arch = "aarch64"
git-tree-sha1 = "a3482584dcb66cdb9fdede0027302708ff28d52c"
libgfortran_version = "5.0.0"
os = "macos"

    [[N2QN1.download]]
    sha256 = "394e821d56758381759127f0eab911127556fc671ec73253808a8a050aec4a3a"
    url = "https://github.com/JuliaBinaryWrappers/N2QN1_jll.jl/releases/download/N2QN1-v4.0.0+0/N2QN1.v4.0.0.aarch64-apple-darwin-libgfortran5.tar.gz"
[[N2QN1]]
arch = "aarch64"
git-tree-sha1 = "01bd4b63da370fd983c7ac9277539fbe18c59ab7"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[N2QN1.download]]
    sha256 = "e05fcc3a0dad114e2114f0d6645666ba3a5a1f55bbfb3af406f40e4d005b4a07"
    url = "https://github.com/JuliaBinaryWrappers/N2QN1_jll.jl/releases/download/N2QN1-v4.0.0+0/N2QN1.v4.0.0.aarch64-linux-gnu-libgfortran3.tar.gz"
[[N2QN1]]
arch = "aarch64"
git-tree-sha1 = "68c9670e7df4083312d6a63cb5554ef157b8bc97"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[N2QN1.download]]
    sha256 = "ae60e2818dade2e1cb63fce8e40f74bb3150db41ef9de2e08ac161d15b97a515"
    url = "https://github.com/JuliaBinaryWrappers/N2QN1_jll.jl/releases/download/N2QN1-v4.0.0+0/N2QN1.v4.0.0.aarch64-linux-gnu-libgfortran4.tar.gz"
[[N2QN1]]
arch = "aarch64"
git-tree-sha1 = "6a008f9424b5609a1508b7b9d3a1fde95ee5e23e"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[N2QN1.download]]
    sha256 = "74dc7e3b7a9c36a92c1fd542fb5afb199d78ec1114da0d4224faf822f66cbb3e"
    url = "https://github.com/JuliaBinaryWrappers/N2QN1_jll.jl/releases/download/N2QN1-v4.0.0+0/N2QN1.v4.0.0.aarch64-linux-gnu-libgfortran5.tar.gz"
[[N2QN1]]
arch = "aarch64"
git-tree-sha1 = "a3e857cfa6edc3df54e52aaa3aace350cc08d219"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[N2QN1.download]]
    sha256 = "b50ca8cd414a64d39f915d14b3abb06a998f8e5f7562db23b29e2ddc68125f08"
    url = "https://github.com/JuliaBinaryWrappers/N2QN1_jll.jl/releases/download/N2QN1-v4.0.0+0/N2QN1.v4.0.0.aarch64-linux-musl-libgfortran3.tar.gz"
[[N2QN1]]
arch = "aarch64"
git-tree-sha1 = "d17fce4a59849e73f99a3060b34259480b618972"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[N2QN1.download]]
    sha256 = "16c195e46e2eb81611697a9482c69f5da5a754ef73319282295ec78a099218cf"
    url = "https://github.com/JuliaBinaryWrappers/N2QN1_jll.jl/releases/download/N2QN1-v4.0.0+0/N2QN1.v4.0.0.aarch64-linux-musl-libgfortran4.tar.gz"
[[N2QN1]]
arch = "aarch64"
git-tree-sha1 = "39903065a0fbbcaac012e2cabd30de08cb50b07a"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[N2QN1.download]]
    sha256 = "72be26a403747e93db9dab28507064003d0b3eb9e1137daece1983a784474258"
    url = "https://github.com/JuliaBinaryWrappers/N2QN1_jll.jl/releases/download/N2QN1-v4.0.0+0/N2QN1.v4.0.0.aarch64-linux-musl-libgfortran5.tar.gz"
[[N2QN1]]
arch = "aarch64"
git-tree-sha1 = "21f62898f5908c304b1c5ae3e469037dc30f128c"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[N2QN1.download]]
    sha256 = "bdaf9289156c129ed86e19efbaec846d802d16686737aa704d7f356f8a952ccb"
    url = "https://github.com/JuliaBinaryWrappers/N2QN1_jll.jl/releases/download/N2QN1-v4.0.0+0/N2QN1.v4.0.0.aarch64-unknown-freebsd-libgfortran5.tar.gz"
[[N2QN1]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6aee688300e51cbb5a4676da1152f4ad9248f75a"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[N2QN1.download]]
    sha256 = "47d7c88822bb7c80ee11668e2f8a94d7850382df6ccbc82aa750eab421320a5a"
    url = "https://github.com/JuliaBinaryWrappers/N2QN1_jll.jl/releases/download/N2QN1-v4.0.0+0/N2QN1.v4.0.0.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[N2QN1]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "0af01b93022f4be7aa5638e512759b76d38921f1"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[N2QN1.download]]
    sha256 = "b81a4daeb104b851ab46a7898c2783be08cd7834c9624b5b518a590796f04c30"
    url = "https://github.com/JuliaBinaryWrappers/N2QN1_jll.jl/releases/download/N2QN1-v4.0.0+0/N2QN1.v4.0.0.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[N2QN1]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6aad49d5aebc582b7da56fefe16ce053f0ad7e38"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[N2QN1.download]]
    sha256 = "73e33b5c98913caef001932fe157b2a802f9bfd4d17184320611c8313764b64f"
    url = "https://github.com/JuliaBinaryWrappers/N2QN1_jll.jl/releases/download/N2QN1-v4.0.0+0/N2QN1.v4.0.0.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[N2QN1]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "dffb861c8e28fa7ee799dc0a92ef582e267ce445"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[N2QN1.download]]
    sha256 = "4ad988b1de7b5c36395b2acfec781ec047479edf253ef677c2c88dc8dfaaf6a4"
    url = "https://github.com/JuliaBinaryWrappers/N2QN1_jll.jl/releases/download/N2QN1-v4.0.0+0/N2QN1.v4.0.0.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[N2QN1]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4299b61b11ec6d9c86d2bd5b25f0f567dd940448"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[N2QN1.download]]
    sha256 = "1d1d0cc62f57f34364ebf5256fff33e080106796da1f8263e68dbf18352288be"
    url = "https://github.com/JuliaBinaryWrappers/N2QN1_jll.jl/releases/download/N2QN1-v4.0.0+0/N2QN1.v4.0.0.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[N2QN1]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6e8c4f8861d474d3db9b4bda29dc1a82ad572be2"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[N2QN1.download]]
    sha256 = "8eb4a05a7504148ea6bbd59cfcaf333318c89dd904dee8710ba3ca181fecbf73"
    url = "https://github.com/JuliaBinaryWrappers/N2QN1_jll.jl/releases/download/N2QN1-v4.0.0+0/N2QN1.v4.0.0.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[N2QN1]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b4d3a1c05fa3935c274fe40fccc926c6e1ba7a22"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[N2QN1.download]]
    sha256 = "84b1ceb24e03048c29658451eb7645557971b41f981c80e40e4fd32ddafc00ec"
    url = "https://github.com/JuliaBinaryWrappers/N2QN1_jll.jl/releases/download/N2QN1-v4.0.0+0/N2QN1.v4.0.0.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[N2QN1]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "80d35d9746f8def318421350f34435425b65d0be"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[N2QN1.download]]
    sha256 = "2cf77cc04062782de6c98636eef83341f1a89d97fbbd3e0879cf5056ffb94542"
    url = "https://github.com/JuliaBinaryWrappers/N2QN1_jll.jl/releases/download/N2QN1-v4.0.0+0/N2QN1.v4.0.0.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[N2QN1]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "abdd58b008a9c67320d902ba2de12f9187ee1768"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[N2QN1.download]]
    sha256 = "b307cee52dbc22a2fa08a388611dc3a5d772c4f2bf887136360ce2aec108d09e"
    url = "https://github.com/JuliaBinaryWrappers/N2QN1_jll.jl/releases/download/N2QN1-v4.0.0+0/N2QN1.v4.0.0.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[N2QN1]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6bf972ea5a3b3d96b3e5c3898039c7d209e1eb6b"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[N2QN1.download]]
    sha256 = "0f4a6fe223dfe499afe7b660e903e4c1999aaf58e307dffe60776bb4938104cd"
    url = "https://github.com/JuliaBinaryWrappers/N2QN1_jll.jl/releases/download/N2QN1-v4.0.0+0/N2QN1.v4.0.0.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[N2QN1]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "50bf4002310e20d82b94f916e2ebe9d0ea740548"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[N2QN1.download]]
    sha256 = "45c1dbb970644bd0b38b7de8ad24d4bfcfdc74b1983bf043ab569e0962a5ca17"
    url = "https://github.com/JuliaBinaryWrappers/N2QN1_jll.jl/releases/download/N2QN1-v4.0.0+0/N2QN1.v4.0.0.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[N2QN1]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5b97b6c8868756e1f6751450d11a4abb62ffc91e"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[N2QN1.download]]
    sha256 = "7d877b84f4667dd500458ac8cdc08892ce8ce74d8ee1135dc21bff966689cddc"
    url = "https://github.com/JuliaBinaryWrappers/N2QN1_jll.jl/releases/download/N2QN1-v4.0.0+0/N2QN1.v4.0.0.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[N2QN1]]
arch = "i686"
git-tree-sha1 = "3891032f6ea25b973096e565ca4d4a42db79fb09"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[N2QN1.download]]
    sha256 = "ab218fc33605fb97ea41a64519b05612f729afa87aaa2ed25a3637546efff151"
    url = "https://github.com/JuliaBinaryWrappers/N2QN1_jll.jl/releases/download/N2QN1-v4.0.0+0/N2QN1.v4.0.0.i686-linux-gnu-libgfortran3.tar.gz"
[[N2QN1]]
arch = "i686"
git-tree-sha1 = "204c60cad59c9937d49306064ed2c1b4ecc351b1"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[N2QN1.download]]
    sha256 = "31724f5a05bbda9b4b3e47a1b120d1d282c1a45cd6d7f62114ce9ca85cfa4e00"
    url = "https://github.com/JuliaBinaryWrappers/N2QN1_jll.jl/releases/download/N2QN1-v4.0.0+0/N2QN1.v4.0.0.i686-linux-gnu-libgfortran4.tar.gz"
[[N2QN1]]
arch = "i686"
git-tree-sha1 = "54732a4e948d6d72063574c639800967354f98ec"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[N2QN1.download]]
    sha256 = "23dc38335783adfe4345de88f8822166179f926c1f19c28e2fdd2a6c9120a9d3"
    url = "https://github.com/JuliaBinaryWrappers/N2QN1_jll.jl/releases/download/N2QN1-v4.0.0+0/N2QN1.v4.0.0.i686-linux-gnu-libgfortran5.tar.gz"
[[N2QN1]]
arch = "i686"
git-tree-sha1 = "b62306e05fdd6bf2a894726f188ad78d7abd63f1"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[N2QN1.download]]
    sha256 = "25e8df65d2dda0427688160a327581b04fe4a24413e0eb973af172fbff510bac"
    url = "https://github.com/JuliaBinaryWrappers/N2QN1_jll.jl/releases/download/N2QN1-v4.0.0+0/N2QN1.v4.0.0.i686-linux-musl-libgfortran3.tar.gz"
[[N2QN1]]
arch = "i686"
git-tree-sha1 = "59b7c0d747ffefa97cd83aa1d61df73065800117"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[N2QN1.download]]
    sha256 = "77d3289849cbbbb5e3c0c69fed22c7d1de9509686b50f53d37cb2a896e263d57"
    url = "https://github.com/JuliaBinaryWrappers/N2QN1_jll.jl/releases/download/N2QN1-v4.0.0+0/N2QN1.v4.0.0.i686-linux-musl-libgfortran4.tar.gz"
[[N2QN1]]
arch = "i686"
git-tree-sha1 = "5bc29ccb8f13ba82ddfa8af100b62a87e343a766"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[N2QN1.download]]
    sha256 = "63391f821fda4d146a94378f8098d32aea65d6a5fafbc79422c4c4097b609b54"
    url = "https://github.com/JuliaBinaryWrappers/N2QN1_jll.jl/releases/download/N2QN1-v4.0.0+0/N2QN1.v4.0.0.i686-linux-musl-libgfortran5.tar.gz"
[[N2QN1]]
arch = "i686"
git-tree-sha1 = "97e7c26fb051b7c81b27b8528eb80cdf0c0c326e"
libgfortran_version = "3.0.0"
os = "windows"

    [[N2QN1.download]]
    sha256 = "009d8fd102321fa3ee6905e32fe6b20459e5124d218855b801c7fd5cb7893c3e"
    url = "https://github.com/JuliaBinaryWrappers/N2QN1_jll.jl/releases/download/N2QN1-v4.0.0+0/N2QN1.v4.0.0.i686-w64-mingw32-libgfortran3.tar.gz"
[[N2QN1]]
arch = "i686"
git-tree-sha1 = "61a44dc434b72ae2c917ad8fcba3eece561716cf"
libgfortran_version = "4.0.0"
os = "windows"

    [[N2QN1.download]]
    sha256 = "66f6e609cae9a360c1f03fbe7ecc33fbf93d9d3e285799a0be5115f3b5634c99"
    url = "https://github.com/JuliaBinaryWrappers/N2QN1_jll.jl/releases/download/N2QN1-v4.0.0+0/N2QN1.v4.0.0.i686-w64-mingw32-libgfortran4.tar.gz"
[[N2QN1]]
arch = "i686"
git-tree-sha1 = "d7d65d91e8df0ee55dd51a97bbafff531a96e9ef"
libgfortran_version = "5.0.0"
os = "windows"

    [[N2QN1.download]]
    sha256 = "5e25bd73adf534074bea39c8bae5cbc182fe1089b88548171ed4aba0d10f700f"
    url = "https://github.com/JuliaBinaryWrappers/N2QN1_jll.jl/releases/download/N2QN1-v4.0.0+0/N2QN1.v4.0.0.i686-w64-mingw32-libgfortran5.tar.gz"
[[N2QN1]]
arch = "powerpc64le"
git-tree-sha1 = "8786b29e7f775fa5d19a49edac983a984a8c7208"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[N2QN1.download]]
    sha256 = "7bda6d0ec0b0fe5374c6fbb2620ce25c3985a89b5b122bbbcd8bf8dfd4d86b83"
    url = "https://github.com/JuliaBinaryWrappers/N2QN1_jll.jl/releases/download/N2QN1-v4.0.0+0/N2QN1.v4.0.0.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[N2QN1]]
arch = "powerpc64le"
git-tree-sha1 = "e7ef690405da9bf7ee08a3acd8778f4f3b4be7e4"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[N2QN1.download]]
    sha256 = "17aa1d674787e0c1b957da44266ce22f4478c96c074de4a96bfb43f807d86b6c"
    url = "https://github.com/JuliaBinaryWrappers/N2QN1_jll.jl/releases/download/N2QN1-v4.0.0+0/N2QN1.v4.0.0.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[N2QN1]]
arch = "powerpc64le"
git-tree-sha1 = "a48a88118f7c09c6bb54cda6841a293231cd74f5"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[N2QN1.download]]
    sha256 = "02248a4788be806a80ddc558c3a2b07e2e361f65afb9387d6bdd2d63acccae5f"
    url = "https://github.com/JuliaBinaryWrappers/N2QN1_jll.jl/releases/download/N2QN1-v4.0.0+0/N2QN1.v4.0.0.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[N2QN1]]
arch = "riscv64"
git-tree-sha1 = "7f7f6719c7acba458b7214b5ab41f5c52334f87f"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[N2QN1.download]]
    sha256 = "05c716252f2b97ce4614ba64b486a823fc0150f3fe4e81308510490a8f49fd6c"
    url = "https://github.com/JuliaBinaryWrappers/N2QN1_jll.jl/releases/download/N2QN1-v4.0.0+0/N2QN1.v4.0.0.riscv64-linux-gnu-libgfortran5.tar.gz"
[[N2QN1]]
arch = "x86_64"
git-tree-sha1 = "08af5d159fd8d6a67d7af056f4e1a6c43c432f1e"
libgfortran_version = "3.0.0"
os = "macos"

    [[N2QN1.download]]
    sha256 = "58cf1a0fd49af47b1f48253fa5fafc28c960c72823bf6e7b97d5e2b9e63d8516"
    url = "https://github.com/JuliaBinaryWrappers/N2QN1_jll.jl/releases/download/N2QN1-v4.0.0+0/N2QN1.v4.0.0.x86_64-apple-darwin-libgfortran3.tar.gz"
[[N2QN1]]
arch = "x86_64"
git-tree-sha1 = "d2b354f772470173603dbaf01f0ee574a3b1a071"
libgfortran_version = "4.0.0"
os = "macos"

    [[N2QN1.download]]
    sha256 = "3ebcc7a12cec24e184fdb866999d232ae2ac66d9e9ca65a4a7ca08d7ad1a6af8"
    url = "https://github.com/JuliaBinaryWrappers/N2QN1_jll.jl/releases/download/N2QN1-v4.0.0+0/N2QN1.v4.0.0.x86_64-apple-darwin-libgfortran4.tar.gz"
[[N2QN1]]
arch = "x86_64"
git-tree-sha1 = "b29595a56505fdea085c8b89607139990dc4bef8"
libgfortran_version = "5.0.0"
os = "macos"

    [[N2QN1.download]]
    sha256 = "483ed73d430f0125a890d168e3d9f8f307756e1c6838c6dc721379b828b84165"
    url = "https://github.com/JuliaBinaryWrappers/N2QN1_jll.jl/releases/download/N2QN1-v4.0.0+0/N2QN1.v4.0.0.x86_64-apple-darwin-libgfortran5.tar.gz"
[[N2QN1]]
arch = "x86_64"
git-tree-sha1 = "3b4e74286af0ac527fb67b6ef196f9d24a1f22cc"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[N2QN1.download]]
    sha256 = "ad9d8f4f6d0582119d6e6c7f572b39b94e8d29aa9631359c81715f89f63a2199"
    url = "https://github.com/JuliaBinaryWrappers/N2QN1_jll.jl/releases/download/N2QN1-v4.0.0+0/N2QN1.v4.0.0.x86_64-linux-gnu-libgfortran3.tar.gz"
[[N2QN1]]
arch = "x86_64"
git-tree-sha1 = "52810e0815c76c67c290504bf889ac3605e9f8ce"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[N2QN1.download]]
    sha256 = "0e02ac10cb372454cee70f1aa2a2504b16e23889957e286eb07e0e582aab9618"
    url = "https://github.com/JuliaBinaryWrappers/N2QN1_jll.jl/releases/download/N2QN1-v4.0.0+0/N2QN1.v4.0.0.x86_64-linux-gnu-libgfortran4.tar.gz"
[[N2QN1]]
arch = "x86_64"
git-tree-sha1 = "099dc599596712f0a902c145f1f2ce7eb55ab6c2"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[N2QN1.download]]
    sha256 = "f6af593f848dbe6492074d493b42090408f38ddde16e374f2a14cd9eccb69781"
    url = "https://github.com/JuliaBinaryWrappers/N2QN1_jll.jl/releases/download/N2QN1-v4.0.0+0/N2QN1.v4.0.0.x86_64-linux-gnu-libgfortran5.tar.gz"
[[N2QN1]]
arch = "x86_64"
git-tree-sha1 = "776c2e9e0da53cb4dbaa141db45b0c9d39ad134d"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[N2QN1.download]]
    sha256 = "aa192496accaf16b117573e5657cc6f818f9f1a4f67c098eccb3f59bd21a596b"
    url = "https://github.com/JuliaBinaryWrappers/N2QN1_jll.jl/releases/download/N2QN1-v4.0.0+0/N2QN1.v4.0.0.x86_64-linux-musl-libgfortran3.tar.gz"
[[N2QN1]]
arch = "x86_64"
git-tree-sha1 = "a4f6952a0df6c9e79638fad8b9ff6212465b44d5"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[N2QN1.download]]
    sha256 = "753e43008c5eaf6ed686029904ecae3bb4c3653b0eaa55d9b30830dbebc9957f"
    url = "https://github.com/JuliaBinaryWrappers/N2QN1_jll.jl/releases/download/N2QN1-v4.0.0+0/N2QN1.v4.0.0.x86_64-linux-musl-libgfortran4.tar.gz"
[[N2QN1]]
arch = "x86_64"
git-tree-sha1 = "e421f14225b0d1c934630ea594399c272ea24688"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[N2QN1.download]]
    sha256 = "67ac5c774b2070309eecaabc411f56cd0f25ec090b36501c5defbe7cd5346c3b"
    url = "https://github.com/JuliaBinaryWrappers/N2QN1_jll.jl/releases/download/N2QN1-v4.0.0+0/N2QN1.v4.0.0.x86_64-linux-musl-libgfortran5.tar.gz"
[[N2QN1]]
arch = "x86_64"
git-tree-sha1 = "a0973a001ab21f03db112c03a77679be38cfc04a"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[N2QN1.download]]
    sha256 = "f7f5474c87db5aff300e066b2bcc4f7fbf7cd9e48768861aa29b15008fdc5e75"
    url = "https://github.com/JuliaBinaryWrappers/N2QN1_jll.jl/releases/download/N2QN1-v4.0.0+0/N2QN1.v4.0.0.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[N2QN1]]
arch = "x86_64"
git-tree-sha1 = "cf6e1c297eb6e1eb9e531de8dfbce8c71f6285c0"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[N2QN1.download]]
    sha256 = "237fe58f0aefad0682fc8f918d95a11e14b29d5354967e7e658a14f073276bd9"
    url = "https://github.com/JuliaBinaryWrappers/N2QN1_jll.jl/releases/download/N2QN1-v4.0.0+0/N2QN1.v4.0.0.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[N2QN1]]
arch = "x86_64"
git-tree-sha1 = "6fc80a5417b08db0a4ab3a6e760594acf9d8d82e"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[N2QN1.download]]
    sha256 = "8249f7334bf6ffcba5ceee2a4456bfbd095a80e6aa13225ef1d749c0717a6cf4"
    url = "https://github.com/JuliaBinaryWrappers/N2QN1_jll.jl/releases/download/N2QN1-v4.0.0+0/N2QN1.v4.0.0.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[N2QN1]]
arch = "x86_64"
git-tree-sha1 = "874f1fc46f09dc2004eeec8703f951e0f794cd0c"
libgfortran_version = "3.0.0"
os = "windows"

    [[N2QN1.download]]
    sha256 = "3419ba1c34eb9f2d0197810da4f1f4764b1c4ca6c71376e81d74526386d6a944"
    url = "https://github.com/JuliaBinaryWrappers/N2QN1_jll.jl/releases/download/N2QN1-v4.0.0+0/N2QN1.v4.0.0.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[N2QN1]]
arch = "x86_64"
git-tree-sha1 = "41b0d067af1b990de19384eafdf15016c9df79d6"
libgfortran_version = "4.0.0"
os = "windows"

    [[N2QN1.download]]
    sha256 = "8d1cf9d25301f05a95c71a71833773a28a8f557d5ac08e043f51f4ab0d902159"
    url = "https://github.com/JuliaBinaryWrappers/N2QN1_jll.jl/releases/download/N2QN1-v4.0.0+0/N2QN1.v4.0.0.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[N2QN1]]
arch = "x86_64"
git-tree-sha1 = "e9ebf66f1652b73495753aa9b4b3eb35378f0237"
libgfortran_version = "5.0.0"
os = "windows"

    [[N2QN1.download]]
    sha256 = "74e413bb2f5ba9ed773ee79c25e0d0939c82a95812c1598807b0e7076486721d"
    url = "https://github.com/JuliaBinaryWrappers/N2QN1_jll.jl/releases/download/N2QN1-v4.0.0+0/N2QN1.v4.0.0.x86_64-w64-mingw32-libgfortran5.tar.gz"
