# Autogenerated wrapper script for N2QN1_jll for i686-linux-gnu-libgfortran3
export libn2qn1, libn2qn1r

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("N2QN1")
JLLWrappers.@declare_library_product(libn2qn1, "libn2qn1.so")
JLLWrappers.@declare_library_product(libn2qn1r, "libn2qn1r.so")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libn2qn1,
        "lib/libn2qn1.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libn2qn1r,
        "lib/libn2qn1r.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
